/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatapp;

import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author hesac
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogConnect = new javax.swing.JDialog();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldPort = new javax.swing.JTextField();
        jButtonConnect = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNetworkInterface = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMainMessageContent = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButtonJoinGroup = new javax.swing.JButton();
        jButtonLeaveGroup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldMessage = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();

        jDialogConnect.setMinimumSize(new java.awt.Dimension(403, 271));
        jDialogConnect.setModal(true);

        jButtonConnect.setText("Kết nối");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jLabel2.setText("IP:");

        jLabel3.setText("Port:");

        jLabel4.setText("Network interface");

        javax.swing.GroupLayout jDialogConnectLayout = new javax.swing.GroupLayout(jDialogConnect.getContentPane());
        jDialogConnect.getContentPane().setLayout(jDialogConnectLayout);
        jDialogConnectLayout.setHorizontalGroup(
            jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogConnectLayout.createSequentialGroup()
                .addGroup(jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogConnectLayout.createSequentialGroup()
                        .addGroup(jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogConnectLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2))
                            .addGroup(jDialogConnectLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGap(64, 64, 64)
                        .addGroup(jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAddress)
                            .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDialogConnectLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(jTextFieldNetworkInterface, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogConnectLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonConnect)
                .addGap(160, 160, 160))
        );
        jDialogConnectLayout.setVerticalGroup(
            jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogConnectLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNetworkInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConnect)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaMainMessageContent.setColumns(20);
        jTextAreaMainMessageContent.setRows(5);
        jTextAreaMainMessageContent.setEditable(false);
        jScrollPane1.setViewportView(jTextAreaMainMessageContent);

        jButton1.setText("Gửi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonJoinGroup.setText("Tham gia group");
        jButtonJoinGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJoinGroupActionPerformed(evt);
            }
        });

        jButtonLeaveGroup.setText("Rời group");
        jButtonLeaveGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaveGroupActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên của bạn:");

        jTextFieldMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMessageKeyPressed(evt);
            }
        });

        jLabelStatus.setBackground(new java.awt.Color(255, 51, 51));
        jLabelStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 51, 51));
        jLabelStatus.setText("Không kết nối!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonJoinGroup)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLeaveGroup)
                        .addGap(77, 77, 77)
                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonJoinGroup)
                    .addComponent(jButtonLeaveGroup)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextFieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJoinGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJoinGroupActionPerformed
        jDialogConnect.setVisible(true);
    }//GEN-LAST:event_jButtonJoinGroupActionPerformed

    private void jButtonLeaveGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaveGroupActionPerformed
        try {
            receiverRunner.stopServer();
            jLabelStatus.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonLeaveGroupActionPerformed

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        try {
            if (!jTextFieldAddress.getText().equalsIgnoreCase("") && !jTextFieldPort.getText().equalsIgnoreCase("")) {
                receiverRunner = new ReceiverRunner(jTextFieldAddress.getText(), Integer.parseInt(jTextFieldPort.getText()),jTextFieldNetworkInterface.getText().trim());
                senderRunner = new SenderRunner(jTextFieldAddress.getText(), Integer.parseInt(jTextFieldPort.getText()),jTextFieldNetworkInterface.getText().trim());
            } else {
                receiverRunner = new ReceiverRunner();
                senderRunner = new SenderRunner();
            }
        } catch (NumberFormatException e) {
            receiverRunner = new ReceiverRunner();
            senderRunner = new SenderRunner();
        }

        try {
            if (receiverRunner.isConnected() && senderRunner.isConnected()) {
                jLabelStatus.setVisible(false);
                startReceiveMessage();
            } else {
                jLabelStatus.setVisible(true);
            }
        } catch (Exception e) {
            jLabelStatus.setVisible(true);
        }
        jDialogConnect.setVisible(false);
    }//GEN-LAST:event_jButtonConnectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String name;
            if(jTextFieldName.getText().equalsIgnoreCase("")){
                name = "An danh";
            }else{
                name = jTextFieldName.getText();
            }
            name = "["+name+"] "+ " : ";
            if (!jTextFieldMessage.getText().equalsIgnoreCase("")) {
                senderRunner.send(name+jTextFieldMessage.getText());
                jTextFieldMessage.setText("");
                jTextAreaMainMessageContent.setCaretPosition(jTextAreaMainMessageContent.getDocument().getLength());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMessageKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldMessageKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrameMain f = new JFrameMain();
                f.setVisible(true);
                try {
                    f.jTextAreaMainMessageContent.append(GetInterfaceNetwork.getInterfaceNetwork());
                } catch (Exception e) {
                }
                
            }
        });
    }

    private void startReceiveMessage() {

        try {
            receiverRunner.start();
            Thread thread = new Thread() {
                public void run() {
                    try {
                        while (receiverRunner.isRunning()) {
                            //System.out.println("dome");
                            if (receiverRunner.hasMessage()) {
                                
                                jTextAreaMainMessageContent.append(receiverRunner.getMessage());
                                jTextAreaMainMessageContent.append("\n");
                                jTextAreaMainMessageContent.append("\n");
                                jTextAreaMainMessageContent.setCaretPosition(jTextAreaMainMessageContent.getDocument().getLength());
                            }
                        }
                    } catch (Exception e) {
                    }
                }
            };
            thread.start();
        } catch (Exception e) {
        }
    }

    SenderRunner senderRunner;
    ReceiverRunner receiverRunner;

    public SenderRunner getSenderRunner() {
        return senderRunner;
    }

    public ReceiverRunner getReceiverRunner() {
        return receiverRunner;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public JButton getjButtonConnect() {
        return jButtonConnect;
    }

    public JButton getjButtonJoinGroup() {
        return jButtonJoinGroup;
    }

    public JButton getjButtonLeaveGroup() {
        return jButtonLeaveGroup;
    }

    public JDialog getjDialogConnect() {
        return jDialogConnect;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabelStatus() {
        return jLabelStatus;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTextArea getjTextAreaMainMessageContent() {
        return jTextAreaMainMessageContent;
    }

    public JTextField getjTextFieldAddress() {
        return jTextFieldAddress;
    }

    public JTextField getjTextFieldMessage() {
        return jTextFieldMessage;
    }

    public JTextField getjTextFieldName() {
        return jTextFieldName;
    }

    public JTextField getjTextFieldPort() {
        return jTextFieldPort;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonJoinGroup;
    private javax.swing.JButton jButtonLeaveGroup;
    private javax.swing.JDialog jDialogConnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMainMessageContent;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldMessage;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNetworkInterface;
    private javax.swing.JTextField jTextFieldPort;
    // End of variables declaration//GEN-END:variables
}
